# Classifying Suicidality

In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import textwrap
import seaborn
import re
from tqdm.auto import tqdm
from utility import extract_case_features, extract_linguistic_features

# Traditional Machine Learning
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier

from scipy.sparse import hstack, csr_matrix
import joblib

# Determinism
random_seed = 42

np.random.seed(random_seed)

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [ ]:
df = pd.read_csv("cleaned_suicidality_dataset.csv", keep_default_na=False, index_col=0)

df.head()

In [ ]:
dataset = df.drop(["label"], axis=1)
label = df["label"]

## Dataset Split
We will do a standard 80/20 split for train and test.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(dataset, label, train_size=0.8, random_state=random_seed)

In [ ]:
label_encoder = LabelEncoder()

# Label encoding target labels
y_train = label_encoder.fit_transform(y_train)
y_test = label_encoder.transform(y_test)

# Mapping of labels to encoding
mapping = dict(zip(range(len(label_encoder.classes_)), label_encoder.classes_))

## Traditional Machine Learning Models

### Preprocessing
We first encoding the cleaned text data into a form the model can use.

In [ ]:
# TF-IDF Encoding Text
vectorizer = TfidfVectorizer(ngram_range=(1, 2), max_features=10000)
standard_scaler = StandardScaler()

# Trainset and Testset
train_linguistic_features = X_train.loc[:, "first_person_singular": "has_crying_emoji"]
train_text_traditional = X_train["text_traditional"]

test_linguistic_features = X_test.loc[:, "first_person_singular": "has_crying_emoji"]
test_text_traditional = X_test["text_traditional"]

# Encoding datasets
train_linguistic_encoded = csr_matrix(standard_scaler.fit_transform(train_linguistic_features))
test_linguistic_encoded = csr_matrix(standard_scaler.transform(test_linguistic_features))

train_text_encoded = vectorizer.fit_transform(train_text_traditional)
test_text_encoded = vectorizer.transform(test_text_traditional)

# Combined traditional
X_train_trad = hstack((train_text_encoded, train_linguistic_encoded))
X_test_trad = hstack((test_text_encoded, test_linguistic_encoded))

### Classification Baseline Accuracy
Usually, a good baseline is mapping the probability of the process (the model needs to be better than predicting at random). For this dataset, the labels might be imbalanced, so we will use the probability of getting the greater class as our baseline (the model needs to be better than just predicting the major class).

In [ ]:
baseline_accuracy = df["label"].value_counts(normalize=True).max()

print(f"The baseline accuracy the models need to beat is {baseline_accuracy*100:.2f}%")

### Logistic Regression
Baseline model for classification

In [ ]:
logreg = LogisticRegression(max_iter=1000, random_state=random_seed)
logreg.fit(X_train_trad, y_train)

In [ ]:
initial_accuracy = logreg.score(X_train_trad, y_train)
print(f"Accuracy on the training set is: {initial_accuracy*100:.2f}%")

In [ ]:
y_predicted = logreg.predict(X_train_trad)
report = classification_report(y_train, y_predicted)

print(report)

#### Hyperparameter Tuning

In [ ]:
param_grid_logreg = {
    "penalty": ["l1", "l2"], # Lasso, Ridge, Elasticnet
    "C": np.logspace(-3, 3, 6) # Inverse of lambda
}

# Understand why these are the parameter grid to use.

In [ ]:
logreg_cv = GridSearchCV(LogisticRegression(solver="saga", max_iter=1000, random_state=random_seed), param_grid=param_grid_logreg, cv=5, n_jobs=2, return_train_score=True, verbose=1)

logreg_cv.fit(X_train_trad, y_train)

In [ ]:
logreg_cv_results = pd.DataFrame(logreg_cv.cv_results_)
logreg_cv_results

In [ ]:
train_scores = logreg_cv_results["mean_train_score"]
validation_scores = logreg_cv_results["mean_test_score"]

fig, ax = plt.subplots(figsize=[10,5])
ax.plot(train_scores, label="Train")
ax.plot(validation_scores, label="Validation")
ax.set_title("Train and Validation Accuracy of the Logistic Regression Model")
ax.set_xlabel("Configuration")
ax.set_ylabel("Accuracy")
ax.legend()
plt.show()

In [ ]:
best_params = logreg_cv.best_params_
best_C, best_penalty = best_params["C"], best_params["penalty"]

best_C, best_penalty

In [ ]:
optimized_logreg = LogisticRegression(max_iter=1000, random_state=random_seed, C=best_C, penalty=best_penalty)
optimized_logreg.fit(X_train_trad, y_train)

#### Evaluating on the test set

In [ ]:
test_accuracy = optimized_logreg.score(X_test_trad, y_test)
print(f"Accuracy on the training set is: {test_accuracy*100:.2f}%")

In [ ]:
y_predicted = optimized_logreg.predict(X_test_trad)
report = classification_report(y_test, y_predicted)

print(report)

#### Saving Model Parameters

In [ ]:
joblib.dump(optimized_logreg, "optimized_logreg.joblib")

### Error Analysis

In [ ]:
error_bool = y_predicted != y_test

In [ ]:
logreg_errors = pd.concat([X_test[error_bool].reset_index(drop=True), pd.Series(y_test[error_bool], name="label").map(mapping)], axis=1)

In [ ]:
logreg_errors.head()

In [ ]:
logreg_errors_features = logreg_errors[["has_post", *list(logreg_errors.loc[:,"first_person_singular": "has_crying_emoji"].columns)]]

In [ ]:
logreg_errors["label"].value_counts()

In [ ]:
suicidal_bool = logreg_errors["label"] == "Suicidal"
non_suicidal_bool = logreg_errors["label"] == "Non-Suicidal"

#### Exploring suicidal errors

In [ ]:
logreg_errors_features[suicidal_bool].describe()

In [ ]:
fig, ax = plt.subplots(figsize=[10,10])
ax.boxplot(x=logreg_errors_features[suicidal_bool])
ax.set_xticklabels(logreg_errors_features.columns)
ax.set_title("Distribution of Suicidal Features")
ax.set_xlabel("Feature")
ax.set_ylabel("Values")
plt.xticks(rotation=90)
plt.show()

In [ ]:
suicidal_error_sample = logreg_errors.loc[suicidal_bool, "text_cleaned"].sample(5, random_state=random_seed).reset_index(drop=True)

In [ ]:
for text in suicidal_error_sample:
    print(text)

Based on the random sample, here are some of the things that was noticed.
1. The preprocessing falls short on "censorship", Reddit posters often censor words creatively, "suicide" to "su!c!de", "die" to "unalive." 
2. Some of the false negatives are context-heavy in their suicidality. For example, the meion of razor blades can mean other things, but in this case it means self harm. The dream post inherently doesn't seem "suicida" as well, but in context it can be considered such. TF-IDF falls short in this area as there's no semantic mapping, only frequency indicators.
3. Current feature engineering does not account for unicode emojis, only "emoticons" like :( or :)

In [ ]:
#TODO add improvements and move on.

#### Exploring non-suicidal errors

In [ ]:
logreg_errors_features[non_suicidal_bool].describe()

In [ ]:
fig, ax = plt.subplots(figsize=[10,10])
ax.boxplot(x=logreg_errors_features[non_suicidal_bool])
ax.set_xticklabels(logreg_errors_features.columns)
ax.set_title("Distribution of Suicidal Features")
ax.set_xlabel("Feature")
ax.set_ylabel("Values")
plt.xticks(rotation=90)
plt.show()

In [ ]:
non_suicidal_error_sample = logreg_errors.loc[non_suicidal_bool, "text_cleaned"].sample(5, random_state=random_seed).reset_index(drop=True)

In [ ]:
for text in non_suicidal_error_sample:
    print(text)

Based on the random sample, here are some of the things that was noticed.
1. Limitations of TF-IDF shows immensely here, most of the words contain negative terms but in some instances the context is meant to be upbeat.
2. The last sample appears to be misclassified in the dataset itself. This is due to the data collection process made. The dataset was made by getting posts from suicidal subreddits and non-suicidal subreddits, however, this doesn't guarantee that posts from either class aren't posted in the opposite subreddits.

Given this, multiple preprocessing adjustments will be made, and will be used moving forward.
1. Separate emoticons and emojis as both are used in reddit posts.
    - We install the emoji package to help us with this.
2. Handle censorships.
3. Use context-specific words to help TF-IDF's frequency approach (listing possible self-harm items).

### K-Nearest Neighbors (KNN)

#### Baseline Model

In [ ]:
knnModel = KNeighborsClassifier()
knnModel.fit(X_train_trad, y_train)

initial_accuracy_knn = knnModel.score(X_train_trad, y_train)
print(f"Accuracy on the training set is: {initial_accuracy_knn*100:.2f}%")

In [ ]:
y_predicted = knnModel.predict(X_train_trad)
report = classification_report(y_train, y_predicted)

print(report)

#### Hyperparameter Tuning

In [ ]:
param_grid = {
    "n_neighbors": [1, 3, 5, 7, 9, 11, 13, 15],
    "weights": ["uniform", "distance"],
    "metric": ["euclidean", "cosine"]
}

In [ ]:
knn_cv = GridSearchCV(
    KNeighborsClassifier(),
    param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1,
    return_train_score=True,
    verbose=1
)
knn_cv.fit(X_train_trad, y_train)

print("Best params:", knn_cv.best_params_)
print("Best CV score:", knn_cv.best_score_)

#### Optimized Model

In [ ]:
best_knn_params = knn_cv.best_params_
optimized_knn = KNeighborsClassifier(**best_knn_params)
optimized_knn.fit(X_train_trad, y_train)

#### Evaluating on the Test Set

In [ ]:
test_accuracy_knn = optimized_knn.score(X_test_trad, y_test)
print(f"Accuracy on the test set is: {test_accuracy_knn*100:.2f}%")

In [ ]:
y_predicted = optimized_knn.predict(X_test_trad)
report = classification_report(y_test, y_predicted)
print(report)

### Error Analysis

In [ ]:
error_bool = y_predicted != y_test
knn_errors = pd.concat([X_test[error_bool].reset_index(drop=True), pd.Series(y_test[error_bool], name="label").map(mapping)], axis=1)
knn_errors.head()

knn_errors_features = knn_errors[["has_post", *list(knn_errors.loc[:,"first_person_singular": "has_crying_emoji"].columns)]]
knn_errors["label"].value_counts()

suicidal_bool = knn_errors["label"] == "Suicidal"
non_suicidal_bool = knn_errors["label"] == "Non-Suicidal"

Exploring Suicidal Bools

In [58]:
knn_errors_features[suicidal_bool].describe()

,has_post,first_person_singular,first_person_plural,absolutist_count,negative_emotion,death_related,past_tense,exclamation_count,question_count,upper_word_count,upper_word_ratio,has_positive_emoji,has_negative_emoji,has_crying_emoji
count,246.000000,246.000000,246.000000,246.000000,246.000000,246.000000,246.000000,246.000000,246.000000,246.000000,246.000000,246.000000,246.0,246.0
mean,0.906504,13.321138,1.292683,2.109756,0.215447,0.878049,2.922764,0.264228,0.853659,1.004065,0.014213,0.056911,0.0,0.0
std,0.291720,15.149814,2.522492,2.771603,0.668783,1.212758,4.564965,1.293351,1.528947,3.835918,0.067635,0.232144,0.0,0.0
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
25%,1.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
50%,1.000000,9.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
75%,1.000000,17.000000,1.000000,3.000000,0.000000,1.000000,3.750000,0.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.0
max,1.000000,118.000000,18.000000,21.000000,6.000000,7.000000,34.000000,15.000000,9.000000,49.000000,0.888889,1.000000,0.0,0.0

In [ ]:
fig, ax = plt.subplots(figsize=[10, 10])
ax.boxplot(x=knn_errors_features[suicidal_bool])
ax.set_xticklabels(knn_errors_features.columns, rotation=90)
ax.set_title("KNN Errors — Distribution of Features (Suicidal)")
ax.set_xlabel("Feature")
ax.set_ylabel("Values")
plt.tight_layout()
plt.show()

In [57]:
suicidal_error_sample = (
    knn_errors.loc[suicidal_bool, "text_cleaned"]
    .sample(5, random_state=random_seed)
    .reset_index(drop=True)
)

for i, text in enumerate(suicidal_error_sample):
    print(f"{i+1}.",end=" ")
    print(textwrap.fill(text, width=125))
    print()

1. tried to put a noose around my neck and dangle around a bit from a safe height Yes, I know this sounds stupid. After two
semesters off, tomorrow uni starts again. Sadly I'm currently in a really bad phase, like real bad. I started drinking strong
alcohol in the evenings more often during the week. My derealization is getting worse and worse. When I went shopping
recently (which is really rare), I felt completely out of touch with reality. I'm afraid of losing my sanity. But today was
even more shitty. I didn't sleep very well so i was grumpy in the morning after having trouble getting out of bed. I was very
cold and harsh towards my mom which fucking hurts me and hate myself for my behaviour... We got in a fight and she told me
that she thinks it would be better for her if I would move out. That's how much of a burden i am. So as i was alone that
afternoon today I tried to tie a strand with a fabric belt. it also worked to tie it to my pull-up bar. I put my head in the
noose and (because i was standing) I kept going down with my upper body. I really noticed how it was getting tighter and
tighter. However, I wasn't afraid of suffocating. The biggest worry is if I were ever to do this seriously, That I can't do
this to my mother. Never. I don't want to go into a clinic. I just want to feel good, enjoy life, have friends that care
about me, help people without being scared all the time. I just want to be "normal". I hate it here.

2. Only 2 hours left for me .

3. Was it an attempt or just a dumb move with no deep meaning? sorry if this breaks any rules, and assuming anyone will look at
this; google couldn't help me out here but basically i overdosed in January on a moderate amount of ibuprofen during a mental
health crisis but the fact i'm so unaffected by it kind of has me wondering if it was even real. Been struggling with
depression for a while, currently 15. like, it wasn't really that i was especially upset or anything i was just vibing and
listening to some good music while doing it. It was like a "Lmao lets see if i die or not" but i kind of knew i'd most likely
live? I got it out of my system the next day without any medical intervention or anything. Sometimes it's harder to take
pills because my body just doesn't agree with them when i'm trying to take them, but otherwise i don't really feel much about
it. What should i even call it?

4. I am the comedian I am the one who everybody says makes them smile. I make people laugh. I build them up. I reinforce
positivity. I shine a bright light on every person I encounter. I’ve been called “the happiest guy at (company name)”. I love
giving compliments. Why? Because I know how it feels to need to hear those things. I am the one, who once the adrenaline of
building up others dies down, is in the darkest place. I laugh, I joke, I praise, I do what I do because I want no others to
feel the way I do. But if only they knew...

5. Is there a point? Been stuck in a severe depression for at least 15 years. (I'm 23) My few feelings that I do have are anger,
afraid, sad, and just numb. Work is NOT helping and there are no friends to talk to. I have planned how I want my funeral to
be like but I'm too scared to kill myself. That's the short version, is there a point in all of this?

Exploring Non-Suicidal Bools

In [59]:
knn_errors_features[non_suicidal_bool].describe()

,has_post,first_person_singular,first_person_plural,absolutist_count,negative_emotion,death_related,past_tense,exclamation_count,question_count,upper_word_count,upper_word_ratio,has_positive_emoji,has_negative_emoji,has_crying_emoji
count,233.000000,233.000000,233.000000,233.000000,233.000000,233.000000,233.000000,233.000000,233.000000,233.000000,233.000000,233.000000,233.000000,233.000000
mean,0.965665,20.729614,0.648069,3.000000,0.922747,0.304721,3.476395,0.502146,0.609442,0.686695,0.003227,0.008584,0.038627,0.008584
std,0.182480,19.011789,1.360055,3.338645,1.160799,0.796990,5.468610,1.137619,1.446546,1.514483,0.007575,0.092448,0.193118,0.092448
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,8.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,16.000000,0.000000,2.000000,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,28.000000,1.000000,4.000000,1.000000,0.000000,4.000000,0.000000,1.000000,1.000000,0.003745,0.000000,0.000000,0.000000
max,1.000000,120.000000,9.000000,18.000000,5.000000,8.000000,44.000000,9.000000,12.000000,13.000000,0.049645,1.000000,1.000000,1.000000

In [ ]:
fig, ax = plt.subplots(figsize=[10, 10])
ax.boxplot(x=knn_errors_features[non_suicidal_bool])
ax.set_xticklabels(knn_errors_features.columns, rotation=90)
ax.set_title("KNN Errors — Distribution of Features (Non-Suicidal)")
ax.set_xlabel("Feature")
ax.set_ylabel("Values")
plt.tight_layout()
plt.show()

In [54]:
non_suicidal_error_sample = (
    knn_errors.loc[non_suicidal_bool, "text_cleaned"]
    .sample(5, random_state=random_seed)
    .reset_index(drop=True)
)

for i, text in enumerate(non_suicidal_error_sample):
    print(f"{i+1}.",end=" ")
    print(textwrap.fill(text, width=125))
    print()

1. I didn’t kill myself last night! You can check my last post if you’re interested in seeing why but I had notes written out to
everybody I love in a little notebook. I had the belt died around a metal bar in my closet. I cleaned my room so my family
wouldn’t have to do it. And then... I got scared. I couldn’t do it. I realized if I was too scared to then part of me must
not want to do it. I texted my friend and told her everything, and I’m still here this morning. Edit: thank you all for the
love and support. I’ve been quite busy today but I plan on responding to all of your comments and messages in my inbox later.
Thank you ❤️ Edit 2: I’ve gotten some messages asking- I’m a 16 year old female. I have tried to reach out to my family about
this but they are extremely dismissive. Right now, the only help I have available to me is my friends. I know that situation
is less than ideal but I’m trying to make what I have work. edit 3, almost 3 years later: apparently this got posted
somewhere and people are coming back to it. if anybody cares, i’m 19 now and doing a lot better. a lot of therapy + living
elsewhere + getting clean. i hope all of you are doing well.

2. went into kitchen to make cookies. didn't have butter. burst into tears. i know it's dumb and irrational. i've had this maple
whip that I made a long time ago in the fridge. it's just been sitting in my fridge, taking up so much space. it's tasty, but
i need something to pair it with. i thought it'd be perfect for thumbprint cookies. i started to make them, but i checked,
and there's not enough butter. no white sugar. barely enough brown sugar. it's so stupid, but i love cooking. i'm a good
baker and it's what i do when i'm stressed. my sibling recently moved in with me after years of living very far. they also
love to cook and they've been cooking for everyone. that was what i would do when i don't work evenings, and it was my
favorite hobby. they want to cook, so i've let them, even if that means i don't have my typical hobbies and rituals. i'm so
stressed with feeling like i made the wrong career choice and i need something comforting that makes me feel like i am not
just sinking into the sand. i don't need someone to make the cookies for me. i don't need someone to buy another type. i
don't want to drive to the store and get the ingredients. i wanted to feel real joy and relief with an easy cookie that i put
work into and i could have for dinner tonight. something tangible. soft. handmade. with joy. :'(

3. Is working from home the cheat code for a good life? I recently started a new job working from home. I'll be honest, its been
AMAZING. My love for life has increased significantly ever since getting this job. I wake up at 8am and start work at 8am.
When I have downtime, I don't have to pretend I'm working on an excel document. My downtime = playing Tears of the Kingdom or
Diablo4. I can work from my desk, my bed, and even while I tan outside. This upcoming Monday I plan on working in the woods
while I hammock. Working from home has made life so enjoyable I don't mind when the weekend is over! Working really isn't
much different then having the day off for me. I love working from home. I was thinking about how much it would take for me
to work on-site, and I've came to the conclusion that I'd need at least a 40% increase in salary. Even with a large increase,
I'd still be hesitant to go on-site. My anxiety is also non-existent when working from home because I'm so comfortable. How
do you guys feel about working from home? What would it take for you to go back to working on-site?

4. How do you tease or show confidence in relationships Hi guys. I'm 22F and gone on a couple dates with this one guy and he
says some things that rub me the wrong way... so I wanted to hear other people's experiences. I think there is a fine line
between confidence and cockiness/arrogance. I met this guy like 2 weeks ago, went on 2 dates so far, and here are some things
he has said that I was like 🤔 "I know you're just dying to see me." "I'm sure you're gonna be dying to see me by Saturday so
maybe if you're lucky we'll get together." "You just can't wait to see this handsome guy can you." "I've never got anyone
flowers before the 3rd date, you're lucky I like you." "You better stay on your A game or I'll be bummed." It just rubs me
the wrong way, like... I get occasional teasing here and there but this just comes off as "I'm the man here, you're lucky you
even get to see me." I don't like that. It's the same way with how he has said some things like "No, a girl can never pay
until after the 3-4th date? That's not how it works." When I offered to pay, split the bill, or cover the tip. When I told
him some previous dates I've been on I paid or split, he acted like those guys were outrageous and rude. I pointed out the
fact that the guy always paying isn't fair or equal, and that if a first date doesn't go well then he's just okay to lose
money?? He says that's "what men do." I said it doesn't have to be that way, but he shook his head like I was crazy. Just
rubbed me the wrong way. Is this unreasonable expectations of mine? Am I being unreasonable? How do you flirt or tease? Is he
just teasing and I'm overthinking it? Edit: He is 27. Edit 2: To add since I just thought of these things: he does compliment
me sometimes, calling me cute, adorable, and pretty. Maybe it's just me, but I don't love being called adorable, he says it
like he thinks I'm a child he takes care of... or at least that is how I feel. But he began calling me babe yesterday, too.
And he talks of date ideas for like next *summer*, but then if I agree or suggest my own ideas, he's all like "Oh already
planning dates 6 months out, you must really like me." And in my head I'm like... you just suggested something... And if I
say "maybe, we'll see" or something similar, he goes "What, you don't think we'll make it that long? So difficult." But he
says it like he's joking, so it confuses me because I can't tell if he's like genuinely just joking and weird about it, or if
deep down he means it a little and is upset. It's just so confusing to me sometimes and making me question my feelings and
beliefs because he is very thoughtful and kind, but then he says things like that? But I'm planning to go on my date with him
on Wednesday and if I'm still iffy about it all, I'll let him know things won't work.

5. I’m finally in a healthy relationship I recently got into a relationship and went on my first date in a really long time. My
friends commented that I already seem so much happier than my last relationships and I honestly think that its true. He’s so
open about everything and I don’t have to guess or play games like with my past partners. I finally feel like I have someone
who wants to put in the same effort that I do in a relationship, and I’ve realised that this is how love is supposed to feel:
good, and not a constant state of stress.